name: Send Push Notification

on:
  schedule:
    - cron: "0 23 * * *"   # 한국 08:00
    - cron: "30 11 * * *"  # 한국 20:30
  workflow_dispatch:

jobs:
  send_push:
    runs-on: ubuntu-latest

    steps:
      - name: Send Push
        run: |
          hour=$(date -u +"%H")

          if [ "$hour" = "23" ]; then
            messages=(
              "오늘두 화이팅!"
              "진짜 마니 보고싶어 바부야"
              $'바부야 오늘 하루도 화이팅!\n무서우면 나 안고 있어 사랑해 언제나'
              $'나 영원히 너꺼야\n걱정 마 오늘 하루도 나 안고 있어 자기얌'
            )
          else
            messages=(
              $'오늘 하루도 많이 힘들었찌?\n 수고 많았어 내가 마니 사랑해 자기야'
              "오늘 하루도 많이 수고 했어 고마워"
              $'내가 진짜 마니 사랑해 우리 자기 \n 오늘 하루도 수고 많았어\n악몽은 저리 버려두고 나 안고 푹 자\n진짜 수고 많았어 사랑해 잘자'
              $'잘자 자기야 \n 오늘 하루도 버티느라 고생했어 걱정 마 나 어디 안가고 여기 있을거야 :) \n 언제나 고마워 진짜 마니 사랑해'
            )
          fi

          random_index=$((RANDOM % ${#messages[@]}))
          message="${messages[$random_index]}"

          curl --request POST \
          --url https://onesignal.com/api/v1/notifications \
          --header "Authorization: Basic ${{ secrets.ONESIGNAL_API_KEY }}" \
          --header "Content-Type: application/json" \
          --data "{
            \"app_id\": \"${{ secrets.ONESIGNAL_APP_ID }}\",
            \"included_segments\": [\"All\"],
            \"headings\": {\"en\": \"to.뚜별❤ from.찬영❤\"},
            \"contents\": {\"en\": \"$message\"}
          }"